name: test

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TARGET_BRANCH: main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Fetch'
        run: git fetch origin ${TARGET_BRANCH}

      - name: 'SAM Validate'
        if: contains(github.event_name, 'pull_request')
        run: |
          CURRENT_DIR=`pwd`
          MERGE_BASE=`git show-branch --merge-base origin/${TARGET_BRANCH} HEAD`
          git diff ${MERGE_BASE} HEAD --diff-filter=AM --name-only
          for FILE in $(git diff ${MERGE_BASE} HEAD --diff-filter=AM --name-only -- "*.py") ; do
            cd $(dirname ${FILE}); cd ../
            RES=`\find . -name "*.yaml" -maxdepth 1 2> /dev/null`
            if [ -n "$RES" ]; then
              echo "find template.yaml!"
              cd $CURRENT_DIR
            elif [ -z "$RES" ]; then
              echo "template.yaml is not found"
              cd $CURRENT_DIR
            fi
          done
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
